apiVersion: v1
kind: Service
metadata:
  name: wine-quality-predict-service
spec:
  selector:
    app: wine-quality-predict
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: LoadBalancer
